name: Build, unit test and sonarcloud
on:
  push:
    branches:
      - mnmsm/unit_tests
      - master
      - minimism
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  sonarcloud:
    name: Build, Unit Test, Sonarcloud
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install libopenmpi-dev libnetcdff-dev netcdf-bin \
          libopenblas-dev makedepf90 petsc-dev
          pip install gcovr --upgrade
      - name: build minimism
        run: |
          cd tests
          make UFEMISM_unit_tests
      - name: unit_test
        run: |
          cd tests
          ./UFEMISM_unit_tests
      - name: collect coverage
        run: |
          cd tests
          make coverage 

          cov_pct=`make coverage | head -n 1 | cut -d' ' -f2 | sed 's/.$//'` 
          if (( $cov_pct < 50 )); then
            false; # not enough coverage
          fi

